---
- hosts: localhost
  
  vars_files:
    - vars/variables.yml

  remote_user: root
    
  tasks:
    - name: Create Cloud-Init File
      file:
        path: ansible-cloud-init.yml
        state: touch
    - name: Write Cloud-Init File    
      copy:
        dest: ansible-cloud-init.yml
        content: |
          #cloud-config
          hostname: {{ hostname }}
          ssh_authorized_keys:
            - {{ ssh_key }}
          rancher:
            network:
              interfaces:
                br0:
                  bridge: true
                  dhcp: {{ dhcp }}
                  address: {{ address }}/30
                  gateway: {{ gateway }}
                  mtu: 1500
                eth0:
                  bridge: br0
            console: {{ console }}
          write_files:
            - path: /etc/rc.local
              permissions: "0755"
              owner: root
              content: |
                #!/bin/bash
                echo "I'm doing things on start"
                apt-get -y update
                apt-get -y install python 
